package com.example.utils.events;

public enum EventType {
    NEW_CHATROOM, REMOVE_FRIEND, REQUEST_ACCEPTED, REQUEST_REJECTED , REQUEST_DELETED,
    FRIENDSHIP_ADDED, EVENT_ADDED, SUBSCRIPTION_ADDED, SUBSCRIPTION_DELETED, SUBSCRIPTION_NOTIFICATIONS_CHANGED
}
